version: '2.0'

services:
    cache:
        image: redis:4.0.11-alpine
        command: ["redis-server"]
        ports:
          - 6379:6379

    db:
        image: mcr.microsoft.com/mssql/server:vNext-CTP2.0-ubuntu
        ports:
          - 1433:1433
        volumes: 
            - db:/var/opt/mssql
        environment:
          - ACCEPT_EULA=Y
          - SA_PASSWORD={s{s)em~?kA4#_zj
          - MSSQL_PID=Express

    app:
        image: node:8.12.0-alpine
        user: "node"
        working_dir: /var/docker/app
        environment:
          - NODE_ENV=production
        volumes:
          - ./src:/var/docker/app
        ports:
          - 8080:8080
        command: "npm run start"
        links: 
          - db:db
          - cache:cache

        depends_on:
          - db
          - cache
  
volumes:
    db:
        driver: local

